accounts/kubernetes/spin-sa.yml
This allows the service-account to perform operations on resources that are not literally called "namespaces"
=> fix(k8s): fix service-account permissions to not restrict by name

README.md, plugins/patch-plugin-wait.yml
Jira https://armory.atlassian.net/browse/PUX-179
```
As a potential user of Spinnaker, I would like to know how the spinnaker-kustomize-patches repo helps me configure Spinnaker faster, so that I can adopt Spinnaker for my organization.
The solution is likely linking to our existing documentation, but it couldn't hurt to add a little more exposition in the repo.
Definition of Done:
The spinnaker-kustomize-patches repo answers the following questions
What is the Spinnaker Operator?
If I'm not familiar with Kustomize or Operator, how does this repo accelerate my adoption of Spinnaker?
```
=> docs(readme): add operator and kustomize overview.

armory/patch-dinghy.yml, security/patch-external-authz.yml
provide patch file for turning on fiat with authz against an external provider, and put placeholder in for dinghy SA to use when fiat is enabled.
=> feature(kustomize): fiat and authz with external

expose/ingress-nginx.yml, expose/patch-urls.yml
Change Gate URL to something that works (api/v1) when Gate is
on the same host but different path then Deck.
=> fix(gate): Change URL to something that works

secrets/create-secrets.sh
Now should support spaces inside the secret value (property value)
Now should support any standard string after the initial `=` inside the `secrets.env`
The `create-secrets.sh` is so rarely run that I figured it was ok to have a bit more debug information in there.
=> fix(secret_script): fix create-secrets to be more robust

recipes/kustomization-all.yml, spinnaker_deployment/patch-cloudsql-sidecars.yml
The following sidecar examples:
- Using Google Cloud SQL for Spinnaker database support outside of Google Cloud if desired
- Using a token authentication sidecar to utilize gcloud for authentication to GKE clusters without triggering rate limits
=> feat(sidecars): sidecar examples

expose/patch-cert-manager-ssl.yml, recipes/kustomization-all.yml, secrets/secrets-example.env
Configure deck and gate to utilize TLS provided and kept up to date by cert-manager
=> feat(cert_manager): manage TLS with cert-manager

persistence/patch-sql-clouddriver.yml
Setting encoding=utf8  updates the tables but may cause an error similar to the following
`jOOQ; uncategorized SQLException for SQL [..] for operation '='; nested exception is java.sql.SQLException: Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_unicode_ci,IMPLICIT)`
Since the collation in tables is now utf8mb4_general_ci, but the collation in string expression is utf8mb4_general_ci.
This affects kubesvc mostly
=> feat(sql): Prevent collation errors in queries

deploy.sh
This is needed for unattended installation when one does not want to wait for Spinnaker to come up for the script to exit.
=> feat(watch): Allow user to skip watching Spinnaker

accounts/aws/patch-aws.yml
this error started showing up 2.23.1
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'armoryAWSBakeHandler' defined in URL [jar:file:/opt/rosco/lib/rosco-package-2.23.5.jar!/com/netflix/spinnaker/rosco/providers/aws/ArmoryAWSBakeHandler.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.rosco.providers.aws.ArmoryAWSBakeHandler]: Constructor threw exception; nested exception is software.amazon.awssdk.core.exception.SdkClientException: Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@f5475d7: …
```
=> feat(rosco): added rosco environment variables

accounts/kubernetes/spin-sa.yml
Updated the default credentials for the spin-sa user when deployed in kubernetes. this is attempting to fix an issue when run in Amazon EKS where certain features in the spinnaker UI give permissions errors. Specifically: with the existing permissions I could not delete infrastructure on the infrastructure tab, and I could not use the 'scale (manifest)' step to scale my deployment. following these permissions changes, those features worked without issue.
=> fix(accounts/kubernetes): Updating the default credentials for the spin-sa user in kubernetes

expose/ingress-traefik.yml
If you don't put https in the URL the basic auth login will
result in 400 error because it's trying to go to the http URL.
This forces a redirect to the https URL.
=> fix(traefik): Fix Traefik redirect to https

accounts/kubernetes/spin-sa.yml
Permissions needed to see logs from spinnaker UI, and to scale and delete `ReplicaSet` and `StatefulSet` from spinnaker stages.
=> feat(kubernetes): Added more permissions needed by spinnaker

infrastructure/opa.yml
Clarifies that the namespace definition will not be used when namespace is defined in `kustomization.yml`. Also adjusts the comment block width.
=> doc(opa): Update opa manifest comments.

.gitignore
feat(armory.io): add webhooks to gitignore
Added ignore for webhooks directory in case it is added and base64 encoded credentials are added.
=> feat(armory.io): add webhooks to gitignore

security/patch-external-authz.yml
Config was missing orca key for enabling pipeline permissions.
Add comment about enabling flag in Deck if any kind of AuthN or AuthZ is enabled.
=> fix(pipeline-permissions): Fix config

infrastructure/minio.yml
Fixes a problem with current latest image of "minio not found" error.
=> fix(minio): Use a fixed tag instead of latest

armory/patch-dinghy.yml
Added dinghy's github notifications config to patch-dinghy.yml and updated an old link.
=> feat(dinghy): add dinghy github notifications config and fix old links

armory/patch-dinghy.yml
It was discovered that Dinghy's Slack notifications do not send if Dinghy's Github notifications are disabled. Slack notifications are not affected if Github notifications are enabled or left unconfigured (default enabled).
The workaround is to explicitly enable notifiers in Dinghy's profile when disabling Dinghy's Github notifications.
=> fix(dinghy): allow for dinghy slack notifiers while github slack notifiers are false

plugins/armory-agent/patch-clouddriver-docker.yaml, plugins/armory-agent/patch-clouddriver-repo.yaml, recipes/kustomization-all.yml
- Add a new patch file to install the Scale Agent plugin from a plugin repository.
- Rename existing plugin patch file; append "-docker" because that file pulls a Docker image for installation as an initContainer.
- Update comments
I plan to display the contents of these files in the Scale Agent plugin installation content.
Partial Jira: [RBK-637] [RBK-626] [RBK-617]
[RBK-637]: https://armory.atlassian.net/browse/RBK-637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RBK-626]: https://armory.atlassian.net/browse/RBK-626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RBK-617]: https://armory.atlassian.net/browse/RBK-617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …
=> feat(scaleAgent): add patch for ScaleAgent plugin from repo

targets/kubernetes/default/service-account.yml
Newer versions of Kubernetes don't create service account secrets by default. For the purposes of evaluation we now add the secret to the Service Account documents. This works in <1.24, so making it the default going forward.
=> feat(k8s): add service account secret for k8s 1.24+

targets/kubernetes/default/kustomization.yml, targets/kubernetes/default/service-account-bindings.yml, targets/kubernetes/default/service-account.yml
Otherwise tokens would be shared when combined with the unique-service-account transformer, which is extremely undesirable.
=> refact(k8s): switch to secret generator to support unique tokens

core/probes/kustomization.yml, core/probes/probes.yml
Several pods (typically echo and gate) have difficulty coming up in eks 1.22 due to failing readiness probes.  In such cases, this config can be applied and should resolve the issue.
=> feat(probes): working config for eks 1.22

plugins/oss/pipeline-as-a-code/kustomization.yaml
Confirmed in Slack that it's not used 
https://cloud-armory.slack.com/archives/C02B8H0L3V3/p1683232094038169
=> code(fix): remove literals section

README.md, deploy.sh, infrastructure/mysql.yml, persistence/patch-sql-clouddriver.yml, persistence/patch-sql-front50.yml, persistence/patch-sql-orca.yml, utilities/unique-service-account.yml
- Fix `deploy.sh` script not able to run deploy operator
- Update mysql version to support both AMD and ARM arch
- Fix ClusterRoleBinding generation failure by kustomize
- Missing "namespace" in `ServiceAccount`
- Error message 
```The ClusterRoleBinding "spin-cluster-role-binding-my-suffix-changeme" is invalid: subjects[0].namespace: Required value```
=> feat(ARM): Update service to support MAC M1/M2  (ARM processor), fix minor issue with local setup - SAAS-1953
