armory/spinnaker-kustomize-patches

README.md

Addresses https://github.com/armory/spinnaker-kustomize-patches/issues/8
@MichaelDBrown

doc(readme): Added disclaimer

---

plugins/patch-plugin-wait.yml

some of the lines had tabs instead of spaces

plugins(fix): replace tabs with spaces in a few lines

---

secrets/secrets-example.env
security/patch-per-service-tls.yml

Adding a patch file for enabling TLS on the spinnaker services.

feat(security): Adding TLS Patch

---

core_config/patch-features.yml
core_config/patch-timezone.yml
core_config/patch-version.yml
recipes/kustomization-all.yml

patches for core features like : 
- Overall Spinnaker Version
- Feature flags 
- Timezone displayed in Deck

feat(core_config): timezone & version & features

---

armory/patch-vault-secrets.yml
recipes/kustomization-all.yml

Configure Armory Vault for secrets

feat(armory_vault): armory vault secret engine

---

recipes/kustomization-all.yml
security/patch-fiat-create-app-roles.yml

Fine-grain control of spinnaker application creation or other permissions set at the deployment level

feat(fiat_create_app_roles): Fiat create app roles

---

recipes/kustomization-all.yml
secrets/secrets-example.env
security/patch-google-groups-auth.yml

AuthN and AuthZ through Google Groups and Google OAuth configuration

feat(google_auth): Google Groups auth

---

expose/patch-lb-static-ip.yml
recipes/kustomization-all.yml

Example configuration for exposing spinnaker with Kubernetes service load balancers to a static IP

feat(lb_static_ip): expose using static ip LB

---

accounts/notifications/patch-slack.yaml
persistence/patch-sql-front50.yml

patch was missing the "config:"

fix(kustomize): patch fix for slack and for front50-sql

---

security/patch-basic-auth.yml

Old format for gate security basicform is depreciated and needs to be updated as per Jason McIntosh and Andrew Way
According to internal Armory discussion:
https://cloud-armory.slack.com/archives/CMEHUF72A/p1607532244441000

Update(patch-basic-auth.yml): Update syntax

---

infrastructure/redis.yml
persistence/patch-redis.yml
recipes/kustomization-quickstart.yml

adding infrastructure/redis.yml and persistence/patch-redis.yml to the default quickstart kustomize template.

feat(redis): externalize redis by default

---

infrastructure/mysql.yml

makes its more usable for getting started

fix(mysql): accept all incoming connections and use type:ClusterIP on service

---

accounts/notifications/patch-email.yml
core_config/patch-deck.yml

based on spinnaker.io docs
https://spinnaker.io/setup/features/notifications/#email

feat(notification): adding email notification configuration example

---

armory/patch-terraformer.yml

tested this setup, and it works, but debating between this patches6902 format vs strategicmerge

feat(terraformer): adding gcp cred example

---

accounts/docker/patch-gcr.yml

update comment. "_json_key" is the username for GCR

chore(gcr): Update patch-gcr.yml

---

airgap/README.MD
airgap/bomdownloader.sh
airgap/imagedownloader.sh
airgap/operatorimageudpate.sh
operator/bomdownloader.sh
operator/halyard-local.yml
operator/patch-config.yaml

walkthrough in docs uses these scripts
[BOB-30093]

feat(airgap): added airgap scripts

---

accounts/ci/patch-travisci.yml

adding verified config for travis ci use

feat(armory.io): add travis ci patch

---

README.md

[DOC-365]
[DOC-365]: https://armory.atlassian.net/browse/DOC-365

doc(readme): Rewrite README and update links to Operator docs

---

expose/ingress-nginx.yml
expose/ingress-traefik.yml
expose/patch-urls.yml

Make sure the Gate paths are defined the same way in patch-urls
and ingress-*

fix(gate): Make Gate paths the same

---

security/patch-fiat-create-app-roles.yml
security/patch-file-authz.yml
security/patch-github.yml
security/patch-google-groups-auth.yml
security/patch-oidc.yml
security/patch-saml.yml

Add comment about enabling flag in Deck if any kind of AuthN or AuthZ is enabled.

fix(authN/authZ): Add comment about enabling flag

---

persistence/patch-sql-clouddriver.yml

* Enable unknown-agent-cleanup-agent by default.
* Add sample config for configuring rate limiting.

fix(clouddriver): Update configs

---

core_config/patch-deck.yml

* Update configs in Deck
* Reorder configs into alpha order

fix(deck): Update configs in Deck

---

armory/patch-diagnostics.yml

* Add default stats config that also stops Echo from recreating at
every Spinnaker update
* Enable defaults for telemetry

fix(diag): Update config

---

accounts/kubernetes/spin-sa.yml

fix(kubernetes-spin-sa):indentation line 22

---

armory/patch-terraformer.yml

* Add Gate proxy setting for Terraformer
* Add default service-settings for Terraformer

fix(terraformer): Update config

---

recipes/kustomization-all.yml

Policy is disabled by default, remove 1:= 0 to enable policy

fix(docs): add policy cm to default

---

operator/kustomization.yml

Fixing operator not deploying by default

fix(operator): Comment custom registry options

---

armory/patch-policy-engine-plugin.yml

Add comment on apiVersion if you are using Spinnaker and the Spinnaker Operator. This is for the updated Policy Engine plugin install content

docs(chore): update Docs URLs

---

accounts/git/patch-bitbucket.yml

Support Bitbucket Server personal access token

feat(bitbucket): add token auth credentials support

---

targets/kubernetes/scale-agent/kustomization.yaml
targets/kubernetes/scale-agent/plugin-config.yml
targets/kubernetes/scale-agent/plugin-container-patch.yml
targets/kubernetes/scale-agent/versions/v1-26.yml
targets/kubernetes/scale-agent/versions/v1-27.yml
targets/kubernetes/scale-agent/versions/v1-28.yml

Jira REQ: https://armory.atlassian.net/browse/RBK-654

chore(agent): agent versions upgrade

---

plugins/oss/pipeline-as-a-code/dinghy.yml

docs(fix): remove logging block

---

targets/kubernetes/scale-agent/kustomization.yaml
targets/kubernetes/scale-agent/proxies/envoy/load_balancer/deployment.yaml
targets/kubernetes/scale-agent/proxies/envoy/load_balancer/envoy.yaml
targets/kubernetes/scale-agent/proxies/envoy/load_balancer/kustomization.yaml
targets/kubernetes/scale-agent/proxies/envoy/load_balancer/patch-spin-clouddriver-grpc.yaml
utilities/unique-service-account.yml

Jira REQ: https://armory.atlassian.net/browse/CDSH-61

feat(agent): add envoy proxy between agent and clouddriver

---

plugins/patch-github-integration-plugin.yml

Adding an example patch for the Armory GitHub Integration plugin

chore(plugin): Adding example patch for the GitHub Integration plugin
